Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 15
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job             count    min threads    max threads
------------  -------  -------------  -------------
all                 1              1              1
indel_filter        1              1              1
indel_select        1              1              1
total               3              1              1

Select jobs to execute...

[Thu Oct 21 22:20:33 2021]
rule indel_select:
    input: result_vcfs/combined.vcf.gz, reference/ref.fasta
    output: result_vcfs/combined.indel.vcf.gz
    log: logs/gatk/select/indel.log
    jobid: 23
    resources: tmpdir=/tmp

[Thu Oct 21 22:20:33 2021]
Error in rule indel_select:
    jobid: 23
    output: result_vcfs/combined.indel.vcf.gz
    log: logs/gatk/select/indel.log (check log file(s) for error message)

RuleException:
InvalidURL in line 200 of /data/00/user/user186/Work_flow_of_population_genetics/snakemake/call_snp/Snakefile:
URL can't contain control characters. '/snakemake/snakemake-wrappers/raw/gatk SelectVariants {params.extra} -V {input.vcf} -O {output.vcf}/wrapper.py' (found at least ' ')
  File "/data/00/user/user186/Work_flow_of_population_genetics/snakemake/call_snp/Snakefile", line 200, in __rule_indel_select
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/urllib/request.py", line 214, in urlopen
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/urllib/request.py", line 517, in open
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/urllib/request.py", line 534, in _open
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/urllib/request.py", line 494, in _call_chain
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/urllib/request.py", line 1389, in https_open
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/urllib/request.py", line 1346, in do_open
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/http/client.py", line 1257, in request
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/http/client.py", line 1268, in _send_request
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/http/client.py", line 1102, in putrequest
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/http/client.py", line 1202, in _validate_path
  File "/data/00/user/user186/miniconda3/envs/snp_calling/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data/00/user/user186/Work_flow_of_population_genetics/snakemake/call_snp/.snakemake/log/2021-10-21T222032.076273.snakemake.log
